In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

In [3]:
eyes_cascade = cv2.CascadeClassifier(r"C:\Users\Zenbook\anaconda3\Lib\site-packages\cv2\data\haarcascade_eye.xml")
nose_cascade = cv2.CascadeClassifier(r"C:\Users\Zenbook\Downloads\Nose18x15.xml")

In [4]:
face_cascade = cv2.CascadeClassifier(r"C:\Users\Zenbook\anaconda3\Lib\site-packages\cv2\data\haarcascade_frontalface_default.xml")

In [5]:
img = cv2.imread(r"C:\Users\Zenbook\Downloads\Before.png",-1)
print(img.shape)
glasses = cv2.imread(r"C:\Users\Zenbook\Downloads\glasses (1).png",-1)
mustache = cv2.imread(r"C:\Users\Zenbook\Downloads\mustache (1).png",-1)
print(glasses.shape)

(485, 377, 4)
(221, 483, 4)


In [6]:
faces = face_cascade.detectMultiScale(img,1.3,5)
for(x,y,w,h) in faces:
    roi_color = img[y:y+h , x:x+w]
    eyes = eyes_cascade.detectMultiScale(roi_color , 1.3,5)
    el = []
    for(ex,ey,ew,eh) in eyes:
        el.append((ex,ey,ew,eh))
        roi_eyes = roi_color[ey:ey+eh , ex:ex+ew]
        
    el = sorted(el, key=lambda a: a[0]) 
    print(el)
    ewf = el[1][0] + el[1][2] - el[0][0]
    ehf = el[1][1] + el[1][3] - el[0][1]
    
    print(ewf,ehf)
    
    glasses2 = cv2.resize(glasses.copy(),(int(1.2 *ewf) , int(2*ehf)))
    print(glasses.shape)
    print(glasses2.shape)
    gw,gh,gc = glasses2.shape
    for i in range(0,gw):
        for j in range(0,gh):
            if glasses2[i,j][3] != 0:
                roi_color[int((el[0][1] + el[1][1]) / 3) + i, int((h - gh) / 2) + j] = glasses2[i, j]
               
    nose = nose_cascade.detectMultiScale(roi_color, scaleFactor = 1.5, minNeighbors= 5)
    for(nx,ny,nw,nh) in nose:
        roi_nose = roi_color[ny:ny+nh , nx:nx+nw]
        mustache2 = cv2.resize(mustache.copy(), (nw , int(0.5*ny)))
        
        mw,mh,mc = mustache2.shape
        
        for i in range(0,mw):
            for j in range(0,mh):
                if mustache2[i,j][3]!=0:
                    roi_color[ny + int(nh/2) + i , nx+j] = mustache2[i,j]
        

[(25, 50, 61, 61), (114, 51, 54, 54)]
143 55
(221, 483, 4)
(110, 171, 4)


In [ ]:
img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow("image",img)
img = np.reshape(img, (-1, 3))
print((img))

cv2.waitKey(0)

cv2.destroyAllWindows()

[[219 202 180]
 [220 203 181]
 [219 202 180]
 ...
 [ 19  13  13]
 [ 21  15  15]
 [ 22  15  15]]
