# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [ ]:
print(np.__version__)
print(np.show_config())

#### 3. Create a null vector of size 10

In [ ]:
a=np.zeros(10)

#### 4.  How to find the memory size of any array

In [ ]:
a.size*a.itemsize

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [ ]:
import numpy as np
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [ ]:
a=np.zeros(10)
a[4]=1

#### 7.  Create a vector with values ranging from 10 to 49

In [ ]:
a=np.arange(10,50)

#### 8.  Reverse a vector (first element becomes last)

In [ ]:
a[::-1]

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
a=np.arange(0,9).reshape(3,3)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [ ]:
t=np.nonzero([1,2,0,0,4,0])

#### 11. Create a 3x3 identity matrix

In [ ]:
t=np.eye(3)

#### 12. Create a 3x3x3 array with random values

In [ ]:
t=np.random.random((3,3,3))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
t=np.random.random((10,10))
tmin=t.min()
tmax=t.max()
print(tmin,tmax)

#### 14. Create a random vector of size 30 and find the mean value

In [ ]:
t=np.random.random(30)
m=t.mean()
print(m)

#### 15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
z=np.zeros((4,4))
z=np.pad(z,pad_width=1,constant_values=1)
print(z)

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
a=np.diag(np.arange(1,5),-1)
print(a)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [5]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
