In [20]:
import numpy as np
arr=np.array([[9,8],[6,5,4.2]])
type(arr)

numpy.ndarray

In [21]:
arr.shape

(2,)

In [15]:
arr.ndim

2

In [14]:
arr.size

6

In [18]:
arr.dtype

dtype('float64')

In [23]:
a=np.array([[2,3,4],[6,7,9]],dtype='float')
a

array([[2., 3., 4.],
       [6., 7., 9.]])

In [25]:
b=np.array((34,5,66))
b

array([34,  5, 66])

In [28]:
c=np.zeros((5,6),dtype='int')
c

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [32]:
d=np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
e=np.full((5,6),7, dtype='complex')
e

array([[7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j, 7.+0.j]])

In [42]:
f=np.random.random((2,4))
f

array([[0.13105747, 0.9604705 , 0.01232546, 0.13675527],
       [0.19556965, 0.83394061, 0.23768383, 0.77402825]])

In [45]:
g=np.arange(9,100)
g

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
       94, 95, 96, 97, 98, 99])

In [46]:
h=np.linspace(7,90,34)
h

array([ 7.        ,  9.51515152, 12.03030303, 14.54545455, 17.06060606,
       19.57575758, 22.09090909, 24.60606061, 27.12121212, 29.63636364,
       32.15151515, 34.66666667, 37.18181818, 39.6969697 , 42.21212121,
       44.72727273, 47.24242424, 49.75757576, 52.27272727, 54.78787879,
       57.3030303 , 59.81818182, 62.33333333, 64.84848485, 67.36363636,
       69.87878788, 72.39393939, 74.90909091, 77.42424242, 79.93939394,
       82.45454545, 84.96969697, 87.48484848, 90.        ])

In [50]:
i=np.array([[45,67,89,1],[11,1001,2,3],[46,67,90,6]])
io=i.reshape(4,1,3)
io

array([[[  45,   67,   89]],

       [[   1,   11, 1001]],

       [[   2,    3,   46]],

       [[  67,   90,    6]]])

In [51]:
iio=i.flatten()
iio

array([  45,   67,   89,    1,   11, 1001,    2,    3,   46,   67,   90,
          6])

# slicing


In [80]:
a=np.array([[9,0,8.7,-4],
           [2,45,78,-9],
           [0.8,3,2,1],
           [12,34,-7,8.4]])
t=a[2:3,::3]
t

array([[0.8, 1. ]])

In [58]:
p=a[[2,3,1],[1,0,2]]
p

array([ 3., 12., 78.])

In [60]:
c=a>0
y=a[c]
y

array([ 9. ,  8.7,  2. , 45. , 78. ,  0.8,  3. ,  2. ,  1. , 12. , 34. ,
        8.4])

In [81]:
a=a*2
a.T

array([[ 18. ,   4. ,   1.6,  24. ],
       [  0. ,  90. ,   6. ,  68. ],
       [ 17.4, 156. ,   4. , -14. ],
       [ -8. , -18. ,   2. ,  16.8]])

In [70]:
a.max(axis=1)

array([ 36., 312.,  12., 136.])

In [73]:
a.cumsum(axis=0)

array([[ 36. ,   0. ,  34.8, -16. ],
       [ 44. , 180. , 346.8, -52. ],
       [ 47.2, 192. , 354.8, -48. ],
       [ 95.2, 328. , 326.8, -14.4]])

In [75]:
a=np.array([[1,2],[3,4]])
b=np.array([[9,8],[1,0]])
a.dot(b)

array([[11,  8],
       [31, 24]])

In [76]:
a=([0,np.pi,np.pi/3])
np.sin(a)

array([0.00000000e+00, 1.22464680e-16, 8.66025404e-01])

In [78]:
a=([0,1,2])
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [87]:
np.sort(a,axis=None)

array([-18. , -14. ,  -8. ,   0. ,   1.6,   2. ,   4. ,   4. ,   6. ,
        16.8,  17.4,  18. ,  24. ,  68. ,  90. , 156. ])

In [96]:
dtypes=[('name','S10'),('y',int),('c',float)]
values=[('Kashish',2200,7.8),('ai',2020,9.0)]
a=np.array(values,dtype=dtypes)
np.sort(a,order='y')

array([(b'ai', 2020, 9. ), (b'Kashish', 2200, 7.8)],
      dtype=[('name', 'S10'), ('y', '<i4'), ('c', '<f8')])

In [ ]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]


In [104]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
np.concatenate((a,b),0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [106]:
np.vsplit(a,2)

[array([[1, 2]]), array([[3, 4]])]